# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class AllocationDetails(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = AllocationDetails()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsAllocationDetails(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def AllocationDetailsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # AllocationDetails
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # AllocationDetails
    def MemoryId(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AllocationDetails
    def MemoryOffsetLow(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # AllocationDetails
    def MemoryOffsetHigh(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def AllocationDetailsStart(builder):
    builder.StartObject(3)

def Start(builder):
    AllocationDetailsStart(builder)

def AllocationDetailsAddMemoryId(builder, memoryId):
    builder.PrependUint32Slot(0, memoryId, 0)

def AddMemoryId(builder, memoryId):
    AllocationDetailsAddMemoryId(builder, memoryId)

def AllocationDetailsAddMemoryOffsetLow(builder, memoryOffsetLow):
    builder.PrependUint32Slot(1, memoryOffsetLow, 0)

def AddMemoryOffsetLow(builder, memoryOffsetLow):
    AllocationDetailsAddMemoryOffsetLow(builder, memoryOffsetLow)

def AllocationDetailsAddMemoryOffsetHigh(builder, memoryOffsetHigh):
    builder.PrependUint32Slot(2, memoryOffsetHigh, 0)

def AddMemoryOffsetHigh(builder, memoryOffsetHigh):
    AllocationDetailsAddMemoryOffsetHigh(builder, memoryOffsetHigh)

def AllocationDetailsEnd(builder):
    return builder.EndObject()

def End(builder):
    return AllocationDetailsEnd(builder)
