# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BackendDelegateInlineData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BackendDelegateInlineData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBackendDelegateInlineData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BackendDelegateInlineDataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # BackendDelegateInlineData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BackendDelegateInlineData
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # BackendDelegateInlineData
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # BackendDelegateInlineData
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BackendDelegateInlineData
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def BackendDelegateInlineDataStart(builder):
    builder.StartObject(1)

def Start(builder):
    BackendDelegateInlineDataStart(builder)

def BackendDelegateInlineDataAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def AddData(builder, data):
    BackendDelegateInlineDataAddData(builder, data)

def BackendDelegateInlineDataStartDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartDataVector(builder, numElems):
    return BackendDelegateInlineDataStartDataVector(builder, numElems)

def BackendDelegateInlineDataEnd(builder):
    return builder.EndObject()

def End(builder):
    return BackendDelegateInlineDataEnd(builder)
