# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BackendDelegateDataReference(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BackendDelegateDataReference()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBackendDelegateDataReference(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BackendDelegateDataReferenceBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # BackendDelegateDataReference
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BackendDelegateDataReference
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # BackendDelegateDataReference
    def Index(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def BackendDelegateDataReferenceStart(builder):
    builder.StartObject(2)

def Start(builder):
    BackendDelegateDataReferenceStart(builder)

def BackendDelegateDataReferenceAddLocation(builder, location):
    builder.PrependInt8Slot(0, location, 0)

def AddLocation(builder, location):
    BackendDelegateDataReferenceAddLocation(builder, location)

def BackendDelegateDataReferenceAddIndex(builder, index):
    builder.PrependUint32Slot(1, index, 0)

def AddIndex(builder, index):
    BackendDelegateDataReferenceAddIndex(builder, index)

def BackendDelegateDataReferenceEnd(builder):
    return builder.EndObject()

def End(builder):
    return BackendDelegateDataReferenceEnd(builder)
