# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class BackendDelegate(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = BackendDelegate()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBackendDelegate(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def BackendDelegateBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # BackendDelegate
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # BackendDelegate
    def Id(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # BackendDelegate
    def Processed(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from executorch_flatbuffer.BackendDelegateDataReference import BackendDelegateDataReference
            obj = BackendDelegateDataReference()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BackendDelegate
    def CompileSpecs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch_flatbuffer.CompileSpec import CompileSpec
            obj = CompileSpec()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # BackendDelegate
    def CompileSpecsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # BackendDelegate
    def CompileSpecsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def BackendDelegateStart(builder):
    builder.StartObject(3)

def Start(builder):
    BackendDelegateStart(builder)

def BackendDelegateAddId(builder, id):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(id), 0)

def AddId(builder, id):
    BackendDelegateAddId(builder, id)

def BackendDelegateAddProcessed(builder, processed):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(processed), 0)

def AddProcessed(builder, processed):
    BackendDelegateAddProcessed(builder, processed)

def BackendDelegateAddCompileSpecs(builder, compileSpecs):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(compileSpecs), 0)

def AddCompileSpecs(builder, compileSpecs):
    BackendDelegateAddCompileSpecs(builder, compileSpecs)

def BackendDelegateStartCompileSpecsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartCompileSpecsVector(builder, numElems):
    return BackendDelegateStartCompileSpecsVector(builder, numElems)

def BackendDelegateEnd(builder):
    return builder.EndObject()

def End(builder):
    return BackendDelegateEnd(builder)
