# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ContainerMetadata(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ContainerMetadata()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsContainerMetadata(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ContainerMetadataBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # ContainerMetadata
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ContainerMetadata
    def EncodedInpStr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ContainerMetadata
    def EncodedOutStr(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ContainerMetadataStart(builder):
    builder.StartObject(2)

def Start(builder):
    ContainerMetadataStart(builder)

def ContainerMetadataAddEncodedInpStr(builder, encodedInpStr):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(encodedInpStr), 0)

def AddEncodedInpStr(builder, encodedInpStr):
    ContainerMetadataAddEncodedInpStr(builder, encodedInpStr)

def ContainerMetadataAddEncodedOutStr(builder, encodedOutStr):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(encodedOutStr), 0)

def AddEncodedOutStr(builder, encodedOutStr):
    ContainerMetadataAddEncodedOutStr(builder, encodedOutStr)

def ContainerMetadataEnd(builder):
    return builder.EndObject()

def End(builder):
    return ContainerMetadataEnd(builder)
