# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class EValue(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = EValue()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEValue(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def EValueBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # EValue
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # EValue
    def ValType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # EValue
    def Val(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def EValueStart(builder):
    builder.StartObject(2)

def Start(builder):
    EValueStart(builder)

def EValueAddValType(builder, valType):
    builder.PrependUint8Slot(0, valType, 0)

def AddValType(builder, valType):
    EValueAddValType(builder, valType)

def EValueAddVal(builder, val):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(val), 0)

def AddVal(builder, val):
    EValueAddVal(builder, val)

def EValueEnd(builder):
    return builder.EndObject()

def End(builder):
    return EValueEnd(builder)
