# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExecutionPlan(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExecutionPlan()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExecutionPlan(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ExecutionPlanBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # ExecutionPlan
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExecutionPlan
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExecutionPlan
    def ContainerMetaType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from executorch_flatbuffer.ContainerMetadata import ContainerMetadata
            obj = ContainerMetadata()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExecutionPlan
    def Values(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch_flatbuffer.EValue import EValue
            obj = EValue()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExecutionPlan
    def ValuesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExecutionPlan
    def ValuesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # ExecutionPlan
    def Inputs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ExecutionPlan
    def InputsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # ExecutionPlan
    def InputsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExecutionPlan
    def InputsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # ExecutionPlan
    def Outputs(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # ExecutionPlan
    def OutputsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # ExecutionPlan
    def OutputsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExecutionPlan
    def OutputsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # ExecutionPlan
    def Chains(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch_flatbuffer.Chain import Chain
            obj = Chain()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExecutionPlan
    def ChainsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExecutionPlan
    def ChainsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # ExecutionPlan
    def Operators(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch_flatbuffer.Operator import Operator
            obj = Operator()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExecutionPlan
    def OperatorsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExecutionPlan
    def OperatorsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # ExecutionPlan
    def Delegates(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch_flatbuffer.BackendDelegate import BackendDelegate
            obj = BackendDelegate()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ExecutionPlan
    def DelegatesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExecutionPlan
    def DelegatesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

    # ExecutionPlan
    def NonConstBufferSizes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # ExecutionPlan
    def NonConstBufferSizesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int64Flags, o)
        return 0

    # ExecutionPlan
    def NonConstBufferSizesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ExecutionPlan
    def NonConstBufferSizesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        return o == 0

def ExecutionPlanStart(builder):
    builder.StartObject(9)

def Start(builder):
    ExecutionPlanStart(builder)

def ExecutionPlanAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ExecutionPlanAddName(builder, name)

def ExecutionPlanAddContainerMetaType(builder, containerMetaType):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(containerMetaType), 0)

def AddContainerMetaType(builder, containerMetaType):
    ExecutionPlanAddContainerMetaType(builder, containerMetaType)

def ExecutionPlanAddValues(builder, values):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(values), 0)

def AddValues(builder, values):
    ExecutionPlanAddValues(builder, values)

def ExecutionPlanStartValuesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartValuesVector(builder, numElems):
    return ExecutionPlanStartValuesVector(builder, numElems)

def ExecutionPlanAddInputs(builder, inputs):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(inputs), 0)

def AddInputs(builder, inputs):
    ExecutionPlanAddInputs(builder, inputs)

def ExecutionPlanStartInputsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartInputsVector(builder, numElems):
    return ExecutionPlanStartInputsVector(builder, numElems)

def ExecutionPlanAddOutputs(builder, outputs):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(outputs), 0)

def AddOutputs(builder, outputs):
    ExecutionPlanAddOutputs(builder, outputs)

def ExecutionPlanStartOutputsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOutputsVector(builder, numElems):
    return ExecutionPlanStartOutputsVector(builder, numElems)

def ExecutionPlanAddChains(builder, chains):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(chains), 0)

def AddChains(builder, chains):
    ExecutionPlanAddChains(builder, chains)

def ExecutionPlanStartChainsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartChainsVector(builder, numElems):
    return ExecutionPlanStartChainsVector(builder, numElems)

def ExecutionPlanAddOperators(builder, operators):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(operators), 0)

def AddOperators(builder, operators):
    ExecutionPlanAddOperators(builder, operators)

def ExecutionPlanStartOperatorsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartOperatorsVector(builder, numElems):
    return ExecutionPlanStartOperatorsVector(builder, numElems)

def ExecutionPlanAddDelegates(builder, delegates):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(delegates), 0)

def AddDelegates(builder, delegates):
    ExecutionPlanAddDelegates(builder, delegates)

def ExecutionPlanStartDelegatesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartDelegatesVector(builder, numElems):
    return ExecutionPlanStartDelegatesVector(builder, numElems)

def ExecutionPlanAddNonConstBufferSizes(builder, nonConstBufferSizes):
    builder.PrependUOffsetTRelativeSlot(8, flatbuffers.number_types.UOffsetTFlags.py_type(nonConstBufferSizes), 0)

def AddNonConstBufferSizes(builder, nonConstBufferSizes):
    ExecutionPlanAddNonConstBufferSizes(builder, nonConstBufferSizes)

def ExecutionPlanStartNonConstBufferSizesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartNonConstBufferSizesVector(builder, numElems):
    return ExecutionPlanStartNonConstBufferSizesVector(builder, numElems)

def ExecutionPlanEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExecutionPlanEnd(builder)
