# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ExtraTensorInfo(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ExtraTensorInfo()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsExtraTensorInfo(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ExtraTensorInfoBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # ExtraTensorInfo
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ExtraTensorInfo
    def MutableDataSegmentsIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ExtraTensorInfo
    def FullyQualifiedName(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # ExtraTensorInfo
    def Location(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def ExtraTensorInfoStart(builder):
    builder.StartObject(3)

def Start(builder):
    ExtraTensorInfoStart(builder)

def ExtraTensorInfoAddMutableDataSegmentsIdx(builder, mutableDataSegmentsIdx):
    builder.PrependUint64Slot(0, mutableDataSegmentsIdx, 0)

def AddMutableDataSegmentsIdx(builder, mutableDataSegmentsIdx):
    ExtraTensorInfoAddMutableDataSegmentsIdx(builder, mutableDataSegmentsIdx)

def ExtraTensorInfoAddFullyQualifiedName(builder, fullyQualifiedName):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(fullyQualifiedName), 0)

def AddFullyQualifiedName(builder, fullyQualifiedName):
    ExtraTensorInfoAddFullyQualifiedName(builder, fullyQualifiedName)

def ExtraTensorInfoAddLocation(builder, location):
    builder.PrependInt8Slot(2, location, 0)

def AddLocation(builder, location):
    ExtraTensorInfoAddLocation(builder, location)

def ExtraTensorInfoEnd(builder):
    return builder.EndObject()

def End(builder):
    return ExtraTensorInfoEnd(builder)
