# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FreeCall(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FreeCall()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFreeCall(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def FreeCallBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # FreeCall
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FreeCall
    def ValueIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def FreeCallStart(builder):
    builder.StartObject(1)

def Start(builder):
    FreeCallStart(builder)

def FreeCallAddValueIndex(builder, valueIndex):
    builder.PrependInt32Slot(0, valueIndex, 0)

def AddValueIndex(builder, valueIndex):
    FreeCallAddValueIndex(builder, valueIndex)

def FreeCallEnd(builder):
    return builder.EndObject()

def End(builder):
    return FreeCallEnd(builder)
