# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

class InstructionArguments(object):
    NONE = 0
    KernelCall = 1
    DelegateCall = 2
    MoveCall = 3
    JumpFalseCall = 4
    FreeCall = 5
