# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Instruction(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Instruction()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInstruction(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def InstructionBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # Instruction
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Instruction
    def InstrArgsType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Instruction
    def InstrArgs(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def InstructionStart(builder):
    builder.StartObject(2)

def Start(builder):
    InstructionStart(builder)

def InstructionAddInstrArgsType(builder, instrArgsType):
    builder.PrependUint8Slot(0, instrArgsType, 0)

def AddInstrArgsType(builder, instrArgsType):
    InstructionAddInstrArgsType(builder, instrArgsType)

def InstructionAddInstrArgs(builder, instrArgs):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(instrArgs), 0)

def AddInstrArgs(builder, instrArgs):
    InstructionAddInstrArgs(builder, instrArgs)

def InstructionEnd(builder):
    return builder.EndObject()

def End(builder):
    return InstructionEnd(builder)
