# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class JumpFalseCall(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = JumpFalseCall()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsJumpFalseCall(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def JumpFalseCallBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # JumpFalseCall
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # JumpFalseCall
    def CondValueIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # JumpFalseCall
    def DestinationInstruction(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def JumpFalseCallStart(builder):
    builder.StartObject(2)

def Start(builder):
    JumpFalseCallStart(builder)

def JumpFalseCallAddCondValueIndex(builder, condValueIndex):
    builder.PrependInt32Slot(0, condValueIndex, 0)

def AddCondValueIndex(builder, condValueIndex):
    JumpFalseCallAddCondValueIndex(builder, condValueIndex)

def JumpFalseCallAddDestinationInstruction(builder, destinationInstruction):
    builder.PrependInt32Slot(1, destinationInstruction, 0)

def AddDestinationInstruction(builder, destinationInstruction):
    JumpFalseCallAddDestinationInstruction(builder, destinationInstruction)

def JumpFalseCallEnd(builder):
    return builder.EndObject()

def End(builder):
    return JumpFalseCallEnd(builder)
