# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

class KernelTypes(object):
    NONE = 0
    Null = 1
    Int = 2
    Bool = 3
    Double = 4
    Tensor = 5
    String = 6
    IntList = 7
    DoubleList = 8
    BoolList = 9
    TensorList = 10
    OptionalTensorList = 11
