# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class MoveCall(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MoveCall()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMoveCall(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def MoveCallBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # MoveCall
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MoveCall
    def MoveFrom(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # MoveCall
    def MoveTo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def MoveCallStart(builder):
    builder.StartObject(2)

def Start(builder):
    MoveCallStart(builder)

def MoveCallAddMoveFrom(builder, moveFrom):
    builder.PrependInt32Slot(0, moveFrom, 0)

def AddMoveFrom(builder, moveFrom):
    MoveCallAddMoveFrom(builder, moveFrom)

def MoveCallAddMoveTo(builder, moveTo):
    builder.PrependInt32Slot(1, moveTo, 0)

def AddMoveTo(builder, moveTo):
    MoveCallAddMoveTo(builder, moveTo)

def MoveCallEnd(builder):
    return builder.EndObject()

def End(builder):
    return MoveCallEnd(builder)
