# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Null(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Null()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsNull(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def NullBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # Null
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def NullStart(builder):
    builder.StartObject(0)

def Start(builder):
    NullStart(builder)

def NullEnd(builder):
    return builder.EndObject()

def End(builder):
    return NullEnd(builder)
