# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Program(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Program()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsProgram(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def ProgramBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # Program
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Program
    def Version(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Program
    def ExecutionPlan(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch_flatbuffer.ExecutionPlan import ExecutionPlan
            obj = ExecutionPlan()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Program
    def ExecutionPlanLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Program
    def ExecutionPlanIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

    # Program
    def ConstantBuffer(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch_flatbuffer.Buffer import Buffer
            obj = Buffer()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Program
    def ConstantBufferLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Program
    def ConstantBufferIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Program
    def BackendDelegateData(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch_flatbuffer.BackendDelegateInlineData import BackendDelegateInlineData
            obj = BackendDelegateInlineData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Program
    def BackendDelegateDataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Program
    def BackendDelegateDataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Program
    def Segments(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch_flatbuffer.DataSegment import DataSegment
            obj = DataSegment()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Program
    def SegmentsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Program
    def SegmentsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Program
    def ConstantSegment(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from executorch_flatbuffer.SubsegmentOffsets import SubsegmentOffsets
            obj = SubsegmentOffsets()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Program
    def MutableDataSegments(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch_flatbuffer.SubsegmentOffsets import SubsegmentOffsets
            obj = SubsegmentOffsets()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Program
    def MutableDataSegmentsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Program
    def MutableDataSegmentsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        return o == 0

    # Program
    def NamedData(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from executorch_flatbuffer.NamedData import NamedData
            obj = NamedData()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Program
    def NamedDataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Program
    def NamedDataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        return o == 0

def ProgramStart(builder):
    builder.StartObject(8)

def Start(builder):
    ProgramStart(builder)

def ProgramAddVersion(builder, version):
    builder.PrependUint32Slot(0, version, 0)

def AddVersion(builder, version):
    ProgramAddVersion(builder, version)

def ProgramAddExecutionPlan(builder, executionPlan):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(executionPlan), 0)

def AddExecutionPlan(builder, executionPlan):
    ProgramAddExecutionPlan(builder, executionPlan)

def ProgramStartExecutionPlanVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartExecutionPlanVector(builder, numElems):
    return ProgramStartExecutionPlanVector(builder, numElems)

def ProgramAddConstantBuffer(builder, constantBuffer):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(constantBuffer), 0)

def AddConstantBuffer(builder, constantBuffer):
    ProgramAddConstantBuffer(builder, constantBuffer)

def ProgramStartConstantBufferVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartConstantBufferVector(builder, numElems):
    return ProgramStartConstantBufferVector(builder, numElems)

def ProgramAddBackendDelegateData(builder, backendDelegateData):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(backendDelegateData), 0)

def AddBackendDelegateData(builder, backendDelegateData):
    ProgramAddBackendDelegateData(builder, backendDelegateData)

def ProgramStartBackendDelegateDataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartBackendDelegateDataVector(builder, numElems):
    return ProgramStartBackendDelegateDataVector(builder, numElems)

def ProgramAddSegments(builder, segments):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(segments), 0)

def AddSegments(builder, segments):
    ProgramAddSegments(builder, segments)

def ProgramStartSegmentsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSegmentsVector(builder, numElems):
    return ProgramStartSegmentsVector(builder, numElems)

def ProgramAddConstantSegment(builder, constantSegment):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(constantSegment), 0)

def AddConstantSegment(builder, constantSegment):
    ProgramAddConstantSegment(builder, constantSegment)

def ProgramAddMutableDataSegments(builder, mutableDataSegments):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(mutableDataSegments), 0)

def AddMutableDataSegments(builder, mutableDataSegments):
    ProgramAddMutableDataSegments(builder, mutableDataSegments)

def ProgramStartMutableDataSegmentsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartMutableDataSegmentsVector(builder, numElems):
    return ProgramStartMutableDataSegmentsVector(builder, numElems)

def ProgramAddNamedData(builder, namedData):
    builder.PrependUOffsetTRelativeSlot(7, flatbuffers.number_types.UOffsetTFlags.py_type(namedData), 0)

def AddNamedData(builder, namedData):
    ProgramAddNamedData(builder, namedData)

def ProgramStartNamedDataVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartNamedDataVector(builder, numElems):
    return ProgramStartNamedDataVector(builder, numElems)

def ProgramEnd(builder):
    return builder.EndObject()

def End(builder):
    return ProgramEnd(builder)
