# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class String(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = String()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsString(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def StringBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # String
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # String
    def StringVal(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def StringStart(builder):
    builder.StartObject(1)

def Start(builder):
    StringStart(builder)

def StringAddStringVal(builder, stringVal):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(stringVal), 0)

def AddStringVal(builder, stringVal):
    StringAddStringVal(builder, stringVal)

def StringEnd(builder):
    return builder.EndObject()

def End(builder):
    return StringEnd(builder)
