# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class SubsegmentOffsets(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SubsegmentOffsets()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsSubsegmentOffsets(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def SubsegmentOffsetsBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # SubsegmentOffsets
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SubsegmentOffsets
    def SegmentIndex(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # SubsegmentOffsets
    def Offsets(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # SubsegmentOffsets
    def OffsetsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # SubsegmentOffsets
    def OffsetsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SubsegmentOffsets
    def OffsetsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def SubsegmentOffsetsStart(builder):
    builder.StartObject(2)

def Start(builder):
    SubsegmentOffsetsStart(builder)

def SubsegmentOffsetsAddSegmentIndex(builder, segmentIndex):
    builder.PrependUint32Slot(0, segmentIndex, 0)

def AddSegmentIndex(builder, segmentIndex):
    SubsegmentOffsetsAddSegmentIndex(builder, segmentIndex)

def SubsegmentOffsetsAddOffsets(builder, offsets):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(offsets), 0)

def AddOffsets(builder, offsets):
    SubsegmentOffsetsAddOffsets(builder, offsets)

def SubsegmentOffsetsStartOffsetsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def StartOffsetsVector(builder, numElems):
    return SubsegmentOffsetsStartOffsetsVector(builder, numElems)

def SubsegmentOffsetsEnd(builder):
    return builder.EndObject()

def End(builder):
    return SubsegmentOffsetsEnd(builder)
