# automatically generated by the FlatBuffers compiler, do not modify

# namespace: executorch_flatbuffer

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Tensor(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Tensor()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsTensor(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    @classmethod
    def TensorBufferHasIdentifier(cls, buf, offset, size_prefixed=False):
        return flatbuffers.util.BufferHasIdentifier(buf, offset, b"\x45\x54\x31\x32", size_prefixed=size_prefixed)

    # Tensor
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Tensor
    def ScalarType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Tensor
    def StorageOffset(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

    # Tensor
    def Sizes(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # Tensor
    def SizesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Int32Flags, o)
        return 0

    # Tensor
    def SizesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Tensor
    def SizesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Tensor
    def DimOrder(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # Tensor
    def DimOrderAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # Tensor
    def DimOrderLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Tensor
    def DimOrderIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Tensor
    def RequiresGrad(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

    # Tensor
    def DataBufferIdx(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # Tensor
    def AllocationInfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from executorch_flatbuffer.AllocationDetails import AllocationDetails
            obj = AllocationDetails()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Tensor
    def Layout(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(18))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Tensor
    def ShapeDynamism(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(20))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Tensor
    def ExtraTensorInfo(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(22))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from executorch_flatbuffer.ExtraTensorInfo import ExtraTensorInfo
            obj = ExtraTensorInfo()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def TensorStart(builder):
    builder.StartObject(10)

def Start(builder):
    TensorStart(builder)

def TensorAddScalarType(builder, scalarType):
    builder.PrependInt8Slot(0, scalarType, 0)

def AddScalarType(builder, scalarType):
    TensorAddScalarType(builder, scalarType)

def TensorAddStorageOffset(builder, storageOffset):
    builder.PrependInt32Slot(1, storageOffset, 0)

def AddStorageOffset(builder, storageOffset):
    TensorAddStorageOffset(builder, storageOffset)

def TensorAddSizes(builder, sizes):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(sizes), 0)

def AddSizes(builder, sizes):
    TensorAddSizes(builder, sizes)

def TensorStartSizesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartSizesVector(builder, numElems):
    return TensorStartSizesVector(builder, numElems)

def TensorAddDimOrder(builder, dimOrder):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(dimOrder), 0)

def AddDimOrder(builder, dimOrder):
    TensorAddDimOrder(builder, dimOrder)

def TensorStartDimOrderVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def StartDimOrderVector(builder, numElems):
    return TensorStartDimOrderVector(builder, numElems)

def TensorAddRequiresGrad(builder, requiresGrad):
    builder.PrependBoolSlot(4, requiresGrad, 0)

def AddRequiresGrad(builder, requiresGrad):
    TensorAddRequiresGrad(builder, requiresGrad)

def TensorAddDataBufferIdx(builder, dataBufferIdx):
    builder.PrependUint32Slot(5, dataBufferIdx, 0)

def AddDataBufferIdx(builder, dataBufferIdx):
    TensorAddDataBufferIdx(builder, dataBufferIdx)

def TensorAddAllocationInfo(builder, allocationInfo):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(allocationInfo), 0)

def AddAllocationInfo(builder, allocationInfo):
    TensorAddAllocationInfo(builder, allocationInfo)

def TensorAddLayout(builder, layout):
    builder.PrependInt8Slot(7, layout, 0)

def AddLayout(builder, layout):
    TensorAddLayout(builder, layout)

def TensorAddShapeDynamism(builder, shapeDynamism):
    builder.PrependInt8Slot(8, shapeDynamism, 0)

def AddShapeDynamism(builder, shapeDynamism):
    TensorAddShapeDynamism(builder, shapeDynamism)

def TensorAddExtraTensorInfo(builder, extraTensorInfo):
    builder.PrependUOffsetTRelativeSlot(9, flatbuffers.number_types.UOffsetTFlags.py_type(extraTensorInfo), 0)

def AddExtraTensorInfo(builder, extraTensorInfo):
    TensorAddExtraTensorInfo(builder, extraTensorInfo)

def TensorEnd(builder):
    return builder.EndObject()

def End(builder):
    return TensorEnd(builder)
